steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/task-manager-440013/task-manager', './']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/task-manager-440013/task-manager']
      
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        [
          'run',
          'deploy',
          'task-manager',
          '--image',
          'gcr.io/task-manager-440013/task-manager',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
images:
  - gcr.io/task-manager-440013/task-manager